<style>

</style>
<div class="container-fluid">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0 text-dark">Пользователи</h3>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="row m-2">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Внутренние пользователи системы</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool"><i class="fas fa-user-plus"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <?php
                    /**@var $ListUser Phalcon\Mvc\Model\Resultset\Simple */
                    if ($ListUser->count() > 0):
                        ?>
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>login</th>
                                <th>Роль</th>
                                <th>Пароль</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($ListUser as $usr):
                                /** @var  $usr tableSystemUsers */
                                ?>
                                <tr>
                                    <td><?= $usr->id ?></td>
                                    <td><?= $usr->login ?></td>
                                    <td class="col-10">
                                        <?= implode(',', $usr->roleList) ?>
                                    </td>
                                    <td class="col text-nowrap">
                                        <div class="input-group input-group-sm is-invalid">
                                            <label class="col-form-label" for="editPassword_<?= $usr->id ?>"></label>
                                            <input type="password"
                                                   class="form-control"
                                                   id="editPassword_<?= $usr->id ?>"
                                                   placeholder="Изменить пароль"/>
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                            <span class="input-group-append">
                    <button type="button" class="btn btn-default btn-flat" data-id="<?= $usr->id ?>">
                      <i class="fas fa-edit"></i>
                    </button>
                  </span>
                                            <!--class="form-control " -->
                                        </div>
                                    </td>
                                    <td class="w-auto text-center">

                                        <a href="<?= $this->url->get(
                                            $this->dispatcher->getControllerName() . '/userDel/' . $usr->id) ?>">
                                            <i class="text-danger fas fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <p>Пользователей не существует</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <!-- TODO Необходимо допилить
    <div class="row m-2">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Пользователи AD имеющие доступ</h3>
                </div>
                <div class="card-body">

                </div>
            </div>
        </div>
    </div>
    -->
    <div class="row m-2">
        <div class="col">
            <?php echo $this->getContent(); ?>
        </div>
    </div>
</div>
<script>

    function ShowMessage(title, text, status = 1) {
        switch (status) {
            case 0:
                status = '';
                break;
            case 1:
                status = 'bg-info';
                break;
            case 2:
                status = 'bg-warning';
                break;
            case 3:
                status = 'bg-danger';
                break;
            case 4:
                status = 'bg-success';
                break;
            default:
                status = '';
        }

        $(document).Toasts('create', {
            title: title,
            body: text,
            autoremove: true,
            autohide: true,
            class: status,
            delay: 2000,
        })
    }

    function SavePassword(e) {
        let id = $(this).data('id') | 0;
        if (!(id > 0))
            return;
        try {
            $('#editPassword_' + id).removeClass('is-invalid');
            let newPwd = $('#editPassword_' + id).val();
            if (newPwd.length < 6) {
                throw 'Маловато символов (менне 6)';
            }

            $.ajax({
                type: "POST",
                url: "<?= $this->url->get($this->dispatcher->getControllerName() . '/UserUpdatePassword/') ?>",
                data: {userId: id, NewPwd: newPwd},
                success: function (data) {
                    ShowMessage('Изменения пароля',
                        'Пароль изменен успешно', 4);
                },
                error: function (data) {
                    $('#editPassword_' + id).addClass('is-invalid');
                    ShowMessage('Ошибка изменения пароля', data.responseText, 3);
                },
            });
        } catch (e) {
            $('#editPassword_' + id).addClass('is-invalid');
            ShowMessage('Ошибка изменения пароля', '' + e.toString(), 3);
        }
    }

    $(document).ready(function () {
        $('.btn-flat').on('click', SavePassword);
    });


</script>