<?php

//var_dump($this->view->values);

//["timeconect"]=> int(1603164710) ["duration"]=> int(28) ["A"]=> int(1)
if (empty($this->view->values))
    return;
/*
$arrCalls = array();
foreach ($this->view->values as $key => $row) {
    //$arrCalls[$row['hour']][] = $row;
}*/
//var_dump($arrCalls);

$dayTime = mktime(0, 0, 1,
    (int)date("m", $this->view->values[0]['timeconnect']),
    (int)date("d", $this->view->values[0]['timeconnect']),
    (int)date("Y", $this->view->values[0]['timeconnect']));
/*$timeStart = mktime(0, 0, 0, date("m", $stime), date("d", $stime), date("Y", $stime));
$timeEnd = mktime(23, 59, 59, date("m", $stime), date("d", $stime), date("Y", $stime));*/


$workHour = [
    9, 10, 11, 12, 15, 16, 17, 18
];
$widthBlock = 50;
$heightBlock = 30;
$heightHead = 20;
$hourStart = 8;
$hourEnd = 20;
//preserveAspectRatio="none">
?>


<?php
$svgHead = $svgRow = '';
for ($i = $hourStart; $i <= $hourEnd; $i++): // строим сетку часов
    $position = $widthBlock * ($i - $hourStart); ?>
    <?php $svgHead .= "
            <rect class='calltimeline-header " . (in_array($i, $workHour) ? 'calltimeline-workDay' : '') . "' width='$widthBlock' height='$heightHead'
                  x='$position' y='0'/>
            <text x='" . (int)($position + ($widthBlock / 2)) . "' y='" . (int)($heightHead / 2) . "' 
                text-anchor='middle' 
                size='16px'
                alignment-baseline='middle' vector-effect='non-scaling-stroke'>$i</text>
        "; ?>
    <?php $svgRow .= "
             <rect class='calltimeline-body " . (in_array($i, $workHour) ? 'calltimeline-workDay' : '') . "'
              width='$widthBlock' height='$heightBlock'
              x='$position' y='$heightHead'/>"; ?>
<?php endfor; ?>

<svg height="<?= $heightBlock + $heightHead ?>" width="100%"
     viewBox="0 0 <?= $widthBlock * ($hourEnd - $hourStart + 1) ?> <?= $heightBlock + $heightHead ?>">
    <g>
        <?= $svgHead ?>
    </g>
    <g>
        <?= $svgRow ?>
    </g>
    <g>
        <?php foreach ($this->view->values as $row):
            //$dt=new DateTime('@'.$row['timeconnect']);
            $h = (int)date("G", $row['timeconnect']);// поучаем Час из времени совершения звонка для позицианирования в квадрате
            if ($h < $hourStart || $h > $hourEnd)
                continue;
            $h -= $hourStart;// если начало не с 0
            $deffSec = $dayTime + ($hourStart * 3600); //получили кол. сек до начала шкалы
            $kofColl = (double)$widthBlock / 3600;// получаем коффицент для одной сек.в ячейке
            ?>
            <!--
        <?php
            var_dump($row); ?>
        -->
            <rect class="calltimeline-Call <?=($row['direction']==1)?'calltimeline-in':'calltimeline-out'?>"
                    width='<?= (int)ceil($row['duration'] * $kofColl) ?>' height='30'
                  x='<?= (int)($kofColl * ($row['timeconnect'] - $deffSec)) ?>' y='<?= $heightHead ?>'
                  />
        <?php endforeach; ?>
    </g>
</svg>