<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Система билинга</title>
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/bootstrap.css"); ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/adminlte.css"); ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/Chart.min.css"); ?>">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->url->getStatic("css/all.min.css"); ?>">
    <link rel="stylesheet" href="<?= $this->url->getStatic("css/daterangepicker.css"); ?>">

    <script src="<?= $this->url->getStatic("js/jquery-3.5.1.min.js"); ?>" type="text/javascript"></script>
    <script src="<?= $this->url->getStatic("js/bootstrap.js"); ?>" type="text/javascript"></script>

    <script src="<?= $this->url->getStatic("js/plugins/Chart.js"); ?>" type="text/javascript"></script>
    <script src="<?= $this->url->getStatic("js/plugins/jquery-ui.min.js"); ?>" type="text/javascript"></script>
    <script src="<?= $this->url->getStatic("js/plugins/moment.min.js"); ?>"></script>
    <script src="<?= $this->url->getStatic("js/plugins/daterangepicker.js"); ?>" type="text/javascript"></script>

    <?php $this->assets->outputCss(); ?>
</head>
<body>

<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item ">
                <span class="navbar-text"><?= SecurityPlugin::$currentUserName . ' (' . SecurityPlugin::$currentRoleList . ')' ?></span>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="<?= $this->url->get("Auth/signout"); ?>" role="button"><i
                            class="fas fa-sign-out-alt"></i></a>
            </li>
        </ul>
    </nav>
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <i class="fas fa-tty"></i>
            Система билинговых<br/> отчетов
        </a>
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <?php $menuGroup = \App\Plugin\Menu\MenuPlugin::getMenu();
                //Формируем меню
                if (!empty($menuGroup)): ?>
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <?php
                        foreach ($menuGroup as $menuItem):
                            $subMenuHTML = "";
                            $isSelected = false;
                            $subMenu = \App\Plugin\Menu\MenuPlugin::getMenu($menuItem->id);
                            if (!is_null($subMenu)) {
                                $subMenuHTML = '<ul class="nav nav-treeview">';
                                foreach ($subMenu as $subMenuItem) {
                                    $isSelectedItem = false;
                                    if ($subMenuItem->controller == $this->router->getControllerName()
                                        && $subMenuItem->action == $this->router->getActionName()) {
                                        $isSelected = $isSelectedItem = true;
                                    }
                                    $subMenuHTML .= '<li class="nav-item">
                                    <a href="' . (!empty($subMenuItem->urlPath) ? $this->url->get($subMenuItem->urlPath) : '#') . '" class="nav-link ' . (($isSelectedItem) ? 'active' : '') . '">
                                        <i class="nav-icon ' . $subMenuItem->class . '"></i>
                                        <p>' . $subMenuItem->name . '</p>
                                        
                                    </a>
                                    </li>';
                                }
                                $subMenuHTML .= '</ul>';
                            }
                            ?>
                            <li class="nav-item
                            <?= (empty($subMenuHTML)) ? '' : 'has-treeview'; ?>
                            <?= ($isSelected) ? 'menu-open' : ''; ?>">
                                <a href="<?= (!empty($menuItem->urlPath) ? $this->url->get($menuItem->urlPath) : '#'); ?>"
                                   class="nav-link <?= ($isSelected) ? 'active' : ''; ?>">
                                    <i class="nav-icon <?= $menuItem->class; ?>"></i>
                                    <p><?= $menuItem->name; ?></p>
                                    <?php if (!empty($subMenuHTML)): ?>
                                        <i class="fas fa-angle-left right"></i>
                                    <?php endif; ?>
                                </a>
                                <?= $subMenuHTML ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <?php echo $this->getContent(); ?>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2020 <a href="https://github.com/DaveMaks">Vanuykov M</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 1.0.5
        </div>
    </footer>
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>

<script src="/js/plugins/summernote.min.js"></script>
<script src="/js/plugins/jquery.knob.min.js"></script>
<!-- ./wrapper -->
<script src="/js/adminlte.js"></script>
<?php $this->assets->outputJs(); ?>
<script>

</script>

</body>
</html>