<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Система билинга</title>
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/bootstrap.css"); ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/adminlte.css"); ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->url->getStatic("css/Chart.min.css"); ?>">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->url->getStatic("css/all.min.css"); ?>">
    <link rel="stylesheet" href="<?= $this->url->getStatic("css/daterangepicker.css"); ?>">

    <script src="<?= $this->url->getStatic("js/jquery-3.5.1.min.js"); ?>" type="text/javascript"></script>
    <script src="<?= $this->url->getStatic("js/bootstrap.js"); ?>" type="text/javascript"></script>
    <script src="<?= $this->url->getStatic("js/plugins/jquery-validation/jquery.validate.min.js"); ?>"></script>
    <script src="<?= $this->url->getStatic("js/plugins/jquery-validation/additional-methods.min.js"); ?>"></script>
</head>
<body class="login-page">

<div>
    <!--Controller-->
    <?php echo $this->getContent(); ?>
</div>

</body>
</html>
